// <auto-generated />
using System;
using CardGame.ObserverRoom.Infrastructure.GameDomain;
using CardGame.ObserverRoom.Infrastructure.GameDomain.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardGame.ObserverRoom.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20231125145202_AddActivitySession")]
    partial class AddActivitySession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardGame.ObserverRoom.Entities.ActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ActivitySessions");
                });

            modelBuilder.Entity("CardGame.ObserverRoom.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivitySessionGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("GameState")
                        .HasColumnType("integer");

                    b.Property<string>("JsonDeck")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuskStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("ZuckerbergStrategy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
