// <auto-generated />
using System;
using CardGame.ObserverRoom.Infrastructure.GameDomain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardGame.ObserverRoom.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20231129165141_FixNaming")]
    partial class FixNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardGame.ObserverRoom.Core.GameDomain.Entities.ActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MuskStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ZuckerbergStrategy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ActivitySession", (string)null);
                });

            modelBuilder.Entity("CardGame.ObserverRoom.Core.GameDomain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivitySessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GameResult")
                        .HasColumnType("integer");

                    b.Property<string>("JsonDeck")
                        .HasColumnType("text");

                    b.Property<int>("MuskStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ZuckerbergStrategy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("CardGame.ObserverRoom.Core.GameDomain.Entities.Game", b =>
                {
                    b.HasOne("CardGame.ObserverRoom.Core.GameDomain.Entities.ActivitySession", null)
                        .WithMany("Games")
                        .HasForeignKey("ActivitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGame.ObserverRoom.Core.GameDomain.Entities.ActivitySession", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
